# Generated by Django 5.1.1 on 2024-10-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_carinventory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carinventory", old_name="car_value", new_name="cars_value",
        ),
        migrations.AddField(
            model_name="car", name="bio", field=models.TextField(blank=True, null=True),
        ),
    ]
